In [2]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd. set_option("display.max_columns", None)
%matplotlib inline
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.model_selection import cross_val_score



In [2]:
kernels = ['Polynomial', 'RBF', 'Sigmoid','Linear']#A function which returns the corresponding SVC model
def getClassifier(ktype):
    if ktype == 0:
        # Polynomial kernal
        return SVC(kernel='poly', degree=8, gamma="auto")
    elif ktype == 1:
        # Radial Basis Function kernal
        return SVC(kernel='rbf', gamma="auto")
    elif ktype == 2:
        # Sigmoid kernal
        return SVC(kernel='sigmoid', gamma="auto")
    elif ktype == 3:
        # Linear kernal
        return SVC(kernel='linear', gamma="auto")

In [3]:
df_data=pd.read_csv('train (2).csv',index_col='Sample ID')

In [4]:
df_data.head()

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
Sample ID                                                                     
1           0.335203  -0.784238   1.748584   0.689819   1.345981   2.401481   
2          -0.367194   1.214139  -1.239823   0.913640  -1.108813   0.842107   
3          -0.223586  -0.004247  -0.753329  -0.231245   0.569146   2.014164   
4          -1.436968   1.467864   0.858960   0.139044   0.295012  -1.267011   
5           0.762653   0.087473  -1.692083  -1.777014  -0.349183   1.095108   

           Feature_7  Feature_8  Feature_9  Feature_10  Feature_11  \
Sample ID                                                            
1           0.555230  -0.442050  -0.600957    1.148517   -1.081843   
2           0.402951  -1.328034  -0.092689    0.992582    0.237420   
3           0.251880   0.579509  -0.466785   -1.019790   -1.497666   
4          -0.710657   0.708872   1.522084   -0.258085   -0.862632   
5          -1.475631   0.199484  -0.274836    0.341762   -1.061380   

           Feature_12  Feature_13  Feature_14  Feature_15  Feature_16  \
Sample ID                                                               
1           -0.080346   -0.893925    0.125909   -0.669251    0.375991   
2            0.239849    0.145646    0.357189    1.050989    0.779528   
3            0.785601   -0.920512    1.011891   -0.228755   -1.316154   
4           -1.208628   -0.611804   -0.799102    1.012847   -0.288742   
5           -0.072029   -1.731650   -0.959146   -0.538061    1.394931   

           Feature_17  Feature_18  Feature_19  Feature_20  Feature_21  \
Sample ID                                                               
1           -0.510180   -1.184106    0.084710    0.492114    0.705536   
2           -0.543720    0.519019   -1.052208   -0.909748   -0.574481   
3            0.336124    0.352343    0.283412   -1.247675    1.578960   
4            0.468328   -0.574399   -0.022129    0.443826   -0.892087   
5           -0.377779   -1.017334   -1.305752    1.217770    0.480845   

           Feature_22  Feature_23  Feature_24  Feature_25  Class  
Sample ID                                                         
1           -0.887245   -0.143438   -0.366181    0.662009      6  
2           -1.772828    0.154405   -0.089003   -2.595208      3  
3            0.071201    0.273445   -0.046615    0.522163      6  
4           -0.909954   -0.748736   -1.263272    0.420825      1  
5           -1.170246   -0.932578   -0.447483   -2.974015      5

In [5]:
df=df_data.iloc[:,:25]
label=df_data['Class']
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

In [6]:
df.head()

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
Sample ID                                                                     
1           0.335203  -0.784238   1.748584   0.689819   1.345981   2.401481   
2          -0.367194   1.214139  -1.239823   0.913640  -1.108813   0.842107   
3          -0.223586  -0.004247  -0.753329  -0.231245   0.569146   2.014164   
4          -1.436968   1.467864   0.858960   0.139044   0.295012  -1.267011   
5           0.762653   0.087473  -1.692083  -1.777014  -0.349183   1.095108   

           Feature_7  Feature_8  Feature_9  Feature_10  Feature_11  \
Sample ID                                                            
1           0.555230  -0.442050  -0.600957    1.148517   -1.081843   
2           0.402951  -1.328034  -0.092689    0.992582    0.237420   
3           0.251880   0.579509  -0.466785   -1.019790   -1.497666   
4          -0.710657   0.708872   1.522084   -0.258085   -0.862632   
5          -1.475631   0.199484  -0.274836    0.341762   -1.061380   

           Feature_12  Feature_13  Feature_14  Feature_15  Feature_16  \
Sample ID                                                               
1           -0.080346   -0.893925    0.125909   -0.669251    0.375991   
2            0.239849    0.145646    0.357189    1.050989    0.779528   
3            0.785601   -0.920512    1.011891   -0.228755   -1.316154   
4           -1.208628   -0.611804   -0.799102    1.012847   -0.288742   
5           -0.072029   -1.731650   -0.959146   -0.538061    1.394931   

           Feature_17  Feature_18  Feature_19  Feature_20  Feature_21  \
Sample ID                                                               
1           -0.510180   -1.184106    0.084710    0.492114    0.705536   
2           -0.543720    0.519019   -1.052208   -0.909748   -0.574481   
3            0.336124    0.352343    0.283412   -1.247675    1.578960   
4            0.468328   -0.574399   -0.022129    0.443826   -0.892087   
5           -0.377779   -1.017334   -1.305752    1.217770    0.480845   

           Feature_22  Feature_23  Feature_24  Feature_25  
Sample ID                                                  
1           -0.887245   -0.143438   -0.366181    0.662009  
2           -1.772828    0.154405   -0.089003   -2.595208  
3            0.071201    0.273445   -0.046615    0.522163  
4           -0.909954   -0.748736   -1.263272    0.420825  
5           -1.170246   -0.932578   -0.447483   -2.974015

## Preprocessing the data

In [7]:


df

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
Sample ID                                                                     
1           0.335203  -0.784238   1.748584   0.689819   1.345981   2.401481   
2          -0.367194   1.214139  -1.239823   0.913640  -1.108813   0.842107   
3          -0.223586  -0.004247  -0.753329  -0.231245   0.569146   2.014164   
4          -1.436968   1.467864   0.858960   0.139044   0.295012  -1.267011   
5           0.762653   0.087473  -1.692083  -1.777014  -0.349183   1.095108   
...              ...        ...        ...        ...        ...        ...   
7996        0.797064   0.088848   1.043295  -1.396315   1.653988  -1.805195   
7997       -1.751327   0.683739   0.531284   0.469559  -1.191279   0.138086   
7998       -1.531730   1.239963   0.375153  -0.604610   0.191582   0.452269   
7999       -1.617570   0.943902   0.721368   0.451608  -0.036600  -1.227781   
8000       -0.805792   0.042070   0.538674   0.616728  -0.532901   1.329784   

           Feature_7  Feature_8  Feature_9  Feature_10  Feature_11  \
Sample ID                                                            
1           0.555230  -0.442050  -0.600957    1.148517   -1.081843   
2           0.402951  -1.328034  -0.092689    0.992582    0.237420   
3           0.251880   0.579509  -0.466785   -1.019790   -1.497666   
4          -0.710657   0.708872   1.522084   -0.258085   -0.862632   
5          -1.475631   0.199484  -0.274836    0.341762   -1.061380   
...              ...        ...        ...         ...         ...   
7996        1.241247   0.456813  -1.225886   -0.957586   -1.076288   
7997        0.601826   0.654457   0.335354    0.001699    0.125758   
7998        1.800385   1.061833   0.723109   -0.646498    0.447437   
7999       -0.482090   0.595763   0.887626    0.311302   -0.461585   
8000       -0.629362  -0.344650  -1.271142   -0.877664   -0.541764   

           Feature_12  Feature_13  Feature_14  Feature_15  Feature_16  \
Sample ID                                                               
1           -0.080346   -0.893925    0.125909   -0.669251    0.375991   
2            0.239849    0.145646    0.357189    1.050989    0.779528   
3            0.785601   -0.920512    1.011891   -0.228755   -1.316154   
4           -1.208628   -0.611804   -0.799102    1.012847   -0.288742   
5           -0.072029   -1.731650   -0.959146   -0.538061    1.394931   
...               ...         ...         ...         ...         ...   
7996         0.853435   -1.464985    1.105600    0.560954    0.605745   
7997         0.626734    0.385055   -1.279141    0.487955    0.408078   
7998         0.835180    1.189334   -1.236210    1.155453    0.168089   
7999        -1.425516   -0.597157   -1.427019    0.699018   -0.333077   
8000         0.501905    0.078554    1.099133    0.485645   -0.745095   

           Feature_17  Feature_18  Feature_19  Feature_20  Feature_21  \
Sample ID                                                               
1           -0.510180   -1.184106    0.084710    0.492114    0.705536   
2           -0.543720    0.519019   -1.052208   -0.909748   -0.574481   
3            0.336124    0.352343    0.283412   -1.247675    1.578960   
4            0.468328   -0.574399   -0.022129    0.443826   -0.892087   
5           -0.377779   -1.017334   -1.305752    1.217770    0.480845   
...               ...         ...         ...         ...         ...   
7996         0.079476    1.730655   -0.815702   -0.996693   -2.301435   
7997        -0.332474   -0.225926    0.452193   -0.457241   -0.278441   
7998        -1.100181    0.154117    0.204855   -0.069365    0.191329   
7999         0.110567   -0.292382   -0.078480   -0.055544    0.586420   
8000         0.743691    0.381499   -0.588390   -0.399387    1.213863   

           Feature_22  Feature_23  Feature_24  Feature_25  
Sample ID                                                  
1           -0.887245   -0.143438   -0.366181    0.6

In [ ]:
#from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="Pandas Profiling Report")

In [16]:
label.shape

(8000,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

## Check data for null values and missing values

In [17]:
df.isnull().sum() ## No missing values

0

In [18]:
df.describe()

count    8000.000000
mean        4.475750
std         2.896025
min         0.000000
25%         2.000000
50%         4.000000
75%         7.000000
max         9.000000
Name: Class, dtype: float64

In [ ]:
## to train once in a loop for all the kernels

for i in range(4):
    # Separate data into test and training sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)# Train a SVC model using different kernal
    svclassifier = getClassifier(i) 
    svclassifier.fit(X_train, y_train)# Make prediction
    y_pred = svclassifier.predict(X_test)# Evaluate our model
    print("Evaluation:", kernals[i], "kernel")
    print(classification_report(y_test,y_pred))

In [21]:
 import random
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['rbf']}
parameters = [ {'C':[np.random.uniform(10,11) for num in range(10)], 'kernel':['rbf'], 'degree': [2,3,4,5,6] ,'gamma':[10*random.random() for num in range(10)]} ]
grid = GridSearchCV(SVC(),parameters,refit=parameters,verbose=2)
grid.fit(X_train,y_train)
print(grid.best_estimator_)

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
[CV] C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.4s remaining:    0.0s


[CV]  C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.574116973407516, degree=2, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.574116973407516, degree=2, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.574116973407516, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.5s
[CV] C=10.574116973407516, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.57411

[CV]  C=10.574116973407516, degree=3, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=3, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.574116973407516, degree=3, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf, total=   1.9s
[CV] C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf, total=   1.7s
[CV] C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.574116973407516, degree=3, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.574116973407516, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.574116973407516, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.57411697340

[CV]  C=10.574116973407516, degree=5, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.574116973407516, degree=5, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.574116973407516, degree=5, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf, total=   1.5s
[CV] C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.574116973407516, degree=5, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.574116973407516, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.574116973407516, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.7s
[CV] C=10.574116973407516, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.57411697

[CV]  C=10.616316676998316, degree=2, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.616316676998316, degree=2, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.616316676998316, degree=2, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.5s
[CV] C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.616316676998316, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.7s
[CV] C=10.616316676998316, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.616316676998316, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.61631667

[CV]  C=10.616316676998316, degree=3, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=3, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.616316676998316, degree=3, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.8s
[CV] C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.616316676998316, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.616316676998316, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.616316676998316, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.61631667699

[CV]  C=10.616316676998316, degree=5, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=5, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.616316676998316, degree=5, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.616316676998316, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.616316676998316, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.616316676998316, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.61631

[CV]  C=10.587221043399081, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=2, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.587221043399081, degree=2, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.5s
[CV] C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.587221043399081, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.587221043399081, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.58722104339

[CV]  C=10.587221043399081, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.587221043399081, degree=3, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.587221043399081, degree=3, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.587221043399081, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.587221043399081, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.587221043399081, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.58722104

[CV]  C=10.587221043399081, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.587221043399081, degree=5, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.587221043399081, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.587221043399081, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.587221043399081, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.58722104

[CV]  C=10.967711707593692, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.967711707593692, degree=2, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.967711707593692, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.967711707593692, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.96771170759

[CV]  C=10.967711707593692, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.967711707593692, degree=4, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.967711707593692, degree=4, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.967711707593692, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.967711707593692, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.96771

[CV]  C=10.967711707593692, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=5, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.967711707593692, degree=5, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.5s
[CV] C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.7s
[CV] C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.967711707593692, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.967711707593692, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.967711707593692, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.967711707593692, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.96771170759

[CV]  C=10.839281952839986, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=2, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.839281952839986, degree=2, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.839281952839986, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.839281952839986, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.83928195

[CV]  C=10.839281952839986, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=4, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.839281952839986, degree=4, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.839281952839986, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.839281952839986, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.83928195

[CV]  C=10.839281952839986, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=5, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.839281952839986, degree=5, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.839281952839986, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.839281952839986, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.839281952839986, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.839281952839986, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.83928195283

[CV]  C=10.842561952325276, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=2, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.842561952325276, degree=2, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.842561952325276, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.842561952325276, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.84256

[CV]  C=10.842561952325276, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=4, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.842561952325276, degree=4, gamma=5.916531755781692, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.8s
[CV] C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.842561952325276, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.7s
[CV] C=10.842561952325276, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.842561952325276, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.84256195232

[CV]  C=10.842561952325276, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.842561952325276, degree=5, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.842561952325276, degree=5, gamma=9.602914980347027, kernel=rbf, total=   1.8s
[CV] C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.7s
[CV] C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.842561952325276, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.842561952325276, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.842561952325276, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.842561952325276, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.84256195

[CV]  C=10.481310770057704, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=2, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.481310770057704, degree=2, gamma=2.7848703479545645, kernel=rbf, total=   1.7s
[CV] C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.481310770057704, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.481310770057704, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.48131077

[CV]  C=10.481310770057704, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.7s
[CV] C=10.481310770057704, degree=4, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.481310770057704, degree=4, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.481310770057704, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.481310770057704, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.48131077005

[CV]  C=10.481310770057704, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.481310770057704, degree=6, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.481310770057704, degree=6, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.481310770057704, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.481310770057704, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.481310770057704, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.48131

[CV]  C=10.92096705498879, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=2, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.92096705498879, degree=2, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.7s
[CV] C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.7s
[CV] C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.92096705498879, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.7s
[CV] C=10.92096705498879, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.92096705498879, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.8s
[CV] C=10.92096705498879, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.92096705498879, degree=

[CV]  C=10.92096705498879, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.7s
[CV] C=10.92096705498879, degree=4, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.92096705498879, degree=4, gamma=4.539256357489378, kernel=rbf, total=   1.7s
[CV] C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.9s
[CV] C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.92096705498879, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.92096705498879, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.92096705498879, degr

[CV]  C=10.92096705498879, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.92096705498879, degree=6, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.92096705498879, degree=6, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.5s
[CV] C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.92096705498879, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.92096705498879, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.92096705498879, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.5s
[CV] C=10.92096705498879, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.92096705498879, degr

[CV]  C=10.026703570298617, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=2, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.026703570298617, degree=2, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.026703570298617, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.026703570298617, degree=3, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.026703570298617, degree=3, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=3, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.02670357029

[CV]  C=10.026703570298617, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=4, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.026703570298617, degree=4, gamma=5.563141366794614, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.026703570298617, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=4, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.026703570298617, degree=4, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=4, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.02670

[CV]  C=10.026703570298617, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=6, gamma=5.916531755781692, kernel=rbf 
[CV]  C=10.026703570298617, degree=6, gamma=5.916531755781692, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.026703570298617, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.5s
[CV] C=10.026703570298617, degree=6, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.026703570298617, degree=6, gamma=4.539256357489378, kernel=rbf, total=   1.7s
[CV] C=10.026703570298617, degree=6, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.02670357029

[CV]  C=10.994599665605143, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.994599665605143, degree=2, gamma=9.602914980347027, kernel=rbf 
[CV]  C=10.994599665605143, degree=2, gamma=9.602914980347027, kernel=rbf, total=   1.7s
[CV] C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf, total=   1.6s
[CV] C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf 
[CV]  C=10.994599665605143, degree=3, gamma=4.604107371905302, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=3, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.994599665605143, degree=3, gamma=4.3914881458290065, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=3, gamma=4.3914881458290065, kernel=rbf 
[CV]  C=10.99459966

[CV]  C=10.994599665605143, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=4, gamma=2.7848703479545645, kernel=rbf 
[CV]  C=10.994599665605143, degree=4, gamma=2.7848703479545645, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf 
[CV]  C=10.994599665605143, degree=4, gamma=2.383852725243095, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=4, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.994599665605143, degree=4, gamma=8.257530760872822, kernel=rbf, total=   1.6s
[CV] C=10.994599665605143, degree=4, gamma=8.257530760872822, kernel=rbf 
[CV]  C=10.99459966

[CV]  C=10.994599665605143, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.6s
[CV] C=10.994599665605143, degree=6, gamma=5.522024467176614, kernel=rbf 
[CV]  C=10.994599665605143, degree=6, gamma=5.522024467176614, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf, total=   1.6s
[CV] C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf 
[CV]  C=10.994599665605143, degree=6, gamma=4.539256357489378, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=6, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.994599665605143, degree=6, gamma=5.563141366794614, kernel=rbf, total=   1.5s
[CV] C=10.994599665605143, degree=6, gamma=5.563141366794614, kernel=rbf 
[CV]  C=10.99459966560

[Parallel(n_jobs=1)]: Done 1500 out of 1500 | elapsed: 39.9min finished


SVC(C=10.574116973407516, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma=2.383852725243095,
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)


In [20]:
np.random.uniform(10,11)

10.928636573384496

## Performing the random search 

In [55]:
from sklearn.model_selection import RandomizedSearchCV
rand_list = {"C": stats.uniform(2, 40),
             "gamma": stats.uniform(0.1, 1)}
              
rand_search = RandomizedSearchCV(SVC(), param_distributions = rand_list, n_iter = 200, n_jobs = 4, cv = 4, random_state = 2017) 
rand_search.fit(X_train, y_train) 
rand_search.cv_results_

{'mean_fit_time': array([1.87457007, 1.78441769, 1.91510022, 2.03643733, 1.88244021,
        1.90733373, 1.88819659, 1.81598037, 1.76050824, 2.06648833,
        1.82924366, 2.01208502, 2.04063225, 1.38539153, 1.85887074,
        1.77612978, 1.82901251, 2.04531604, 1.48615211, 1.91456199,
        1.92045373, 1.94017982, 2.00904989, 1.8423121 , 2.05630565,
        1.9529106 , 1.94976258, 2.06238228, 1.89493924, 2.09549004,
        1.92139202, 2.08592045, 1.37316918, 1.96317196, 2.21057022,
        1.99521947, 2.15370816, 1.95521879, 2.06191188, 1.98893428,
        1.95489168, 1.4007355 , 2.03011584, 1.98975503, 1.93204594,
        2.42494464, 2.04687542, 2.02676123, 2.12163967, 2.04625356,
        1.41703051, 2.09877902, 2.31162435, 2.0694117 , 2.1250602 ,
        2.14442062, 2.22403091, 1.9166218 , 1.74311733, 1.94034535,
        1.88104397, 2.08724034, 1.91455603, 1.86058074, 1.80227864,
        2.08066714, 1.9372701 , 2.11465281, 1.93682861, 1.98784524,
        1.98839772, 2.0523845 ,

In [57]:
rand_search.best_estimator_

SVC(C=31.17033310727951, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.10147872446880915,
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [22]:
print(grid.best_estimator_)

SVC(C=10.574116973407516, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma=2.383852725243095,
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)


In [ ]:
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [58]:
grid_predictions = rand_search.predict(X_test)
print(grid_predictions)
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[4 8 7 ... 7 4 6]
[[225   0   0   0   0   2   3   1   0   0]
 [  0 266   2   0   0   0   0   0   0   0]
 [  1   0 245   3   0   0   0   0   1   0]
 [  0   0   0 234   0   5   0   2   0   0]
 [  0   0   0   0 222   0   1   2   0   1]
 [  1   0   0  11   2 199   2   1   2   0]
 [  2   1   0   0   1   1 228   0   0   0]
 [  0   0   0   1   1   0   1 248   0   2]
 [  1   0   1   3   0   1   0   1 227   0]
 [  0   0   4   2   7   0   0   1   0 232]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       231
           1       1.00      0.99      0.99       268
           2       0.97      0.98      0.98       250
           3       0.92      0.97      0.95       241
           4       0.95      0.98      0.97       226
           5       0.96      0.91      0.93       218
           6       0.97      0.98      0.97       233
           7       0.97      0.98      0.97       253
           8       0.99      0.97      0.98       234
          

In [59]:
x_real_test=pd.read_csv('test (1).csv',index_col='Sample ID')
x_real_test

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
Sample ID                                                                     
1           0.036550   0.641572  -0.519057   0.460712   0.570700   0.222309   
2          -1.004027   0.534250  -0.259404   0.310052   0.755525  -0.267865   
3          -1.147219   0.334078  -0.389740  -0.508234   0.184723   1.956903   
4          -0.506680  -1.361191  -0.576784   0.064672  -0.049516  -0.111892   
5          -1.546926   0.966659   0.460473   0.139549  -0.777357  -0.015657   
...              ...        ...        ...        ...        ...        ...   
1996       -1.582811   0.864609   0.612178   0.358372  -1.142419   0.675760   
1997        1.744843   0.623868  -0.469064   1.619294  -0.944036  -0.744784   
1998       -1.745249   0.983623   0.502273   0.282896  -0.758385  -0.294727   
1999       -1.235580  -0.180367   0.232004  -1.738035   0.262606  -0.283989   
2000        0.295303   0.586335  -1.943268   0.487705  -0.199133  -1.727402   

           Feature_7  Feature_8  Feature_9  Feature_10  Feature_11  \
Sample ID                                                            
1           0.087710  -0.318400  -1.973283    0.708141   -0.694613   
2           0.803048   0.824546  -0.017057   -0.439858   -0.445488   
3           1.366785   0.906050  -0.138883   -1.956578    0.269007   
4           0.502428  -0.332201  -1.203807   -1.206357   -0.073538   
5           1.188006   1.035923  -0.326310    0.671796   -0.298746   
...              ...        ...        ...         ...         ...   
1996        0.986953   0.802516  -0.294720    0.286791    0.354213   
1997        0.073100   0.934007  -1.300712    1.010739    0.621316   
1998        0.434684   0.807753   0.797022    0.503041   -0.150811   
1999        1.539323  -0.661559   1.040505    1.726944    0.246581   
2000       -0.849607   0.619744   0.122939    1.732983    1.044651   

           Feature_12  Feature_13  Feature_14  Feature_15  Feature_16  \
Sample ID                                                               
1           -0.012598   -2.175199   -0.715505    1.554487   -1.049741   
2            1.523259    1.173979   -2.521010    0.617056   -0.377550   
3            1.513636   -0.310510    1.485705    0.512841    0.316459   
4           -1.186343    0.429413   -1.702328   -0.721962   -0.187222   
5            0.897230   -0.122893   -1.581675    0.471695    0.404783   
...               ...         ...         ...         ...         ...   
1996         1.393753    0.245489   -0.211728    0.827078    0.592820   
1997        -0.981961    1.733346   -0.443691    1.345635   -1.452097   
1998        -0.003568    0.104631   -1.618550    1.071597    0.058739   
1999        -0.643062    0.258146   -0.157697   -0.914946    0.455763   
2000         1.102488    0.256830    0.688361   -1.457985    1.857233   

           Feature_17  Feature_18  Feature_19  Feature_20  Feature_21  \
Sample ID                                                               
1           -1.672266    1.059074    0.206516    0.792531    0.844650   
2            0.455779   -1.574711   -0.374946    1.361794   -0.062464   
3           -1.694966   -0.511869    0.123451   -1.174886    0.341067   
4           -1.211090   -1.062384   -0.162851    1.043950    0.482891   
5           -0.386269   -0.727555    0.454785   -1.020171    0.171097   
...               ...         ...         ...         ...         ...   
1996        -0.717194   -0.008238    0.278941   -1.016759    0.229739   
1997         0.099856    0.092569    0.828947   -0.176099    0.073565   
1998        -0.481010   -0.342823    0.254859    0.080882    0.159286   
1999        -1.096604    0.034090    0.154824    0.432887    1.724974   
2000        -0.413658   -2.137722    0.697366    1.741294    1.250204   

           Feature_22  Feature_23  Feature_24  Feature_25  
Sample ID                                                  
1           -0.784680    0.937180    0.043382    0.5

In [60]:

ans=rand_search.predict(x_real_test)
sample_id=[i for i in range(1,len(ans)+1)]
dicta={'Sample ID':sample_id,'Class':ans,}
dicta

{'Sample ID': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  1

In [49]:
df_ans['Sample ID']

0          1
1          2
2          3
3          4
4          5
        ... 
1995    1996
1996    1997
1997    1998
1998    1999
1999    2000
Name: Sample ID, Length: 2000, dtype: int64

In [61]:
df_ans = pd.DataFrame(dicta)
#print(df_ans.head())
df_ans.to_csv('ans9.csv', header=True)

In [62]:
ans2=pd.read_csv('ans9.csv')
ans2.head()

Unnamed: 0  Sample ID  Class
0           0          1      8
1           1          2      7
2           2          3      1
3           3          4      7
4           4          5      1

In [91]:
print(grid.best_params_)
print(grid.best_estimator_.get_params())

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
{'C': 10, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 0.1, 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}


# Linear kernel

In [74]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'linear', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.983


In [77]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'sigmoid', random_state=1, C=0.021,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.972


In [61]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'rbf', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
#('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))
#The smaller the value of C, the wider the margins – which may lead to more misclassifications.
##Inversely, the larger the value of C, the more narrow the margins of the classifier become – this may lead to fewer misclassifications
# but higher values of c leads to overfitting

Training set score: 0.9714
Test set score: 0.9778


In [69]:
ex=X_test.iloc[25,:]
ex=ex.values.reshape(-1,10)

In [70]:
svm.predict(ex)

array([2], dtype=int64)

In [ ]:
ex=ex.reshape(-1,25)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[88  2]
 [ 2 88]]
              precision    recall  f1-score   support

           2       0.98      0.98      0.98        90
           7       0.98      0.98      0.98        90

    accuracy                           0.98       180
   macro avg       0.98      0.98      0.98       180
weighted avg       0.98      0.98      0.98       180



## Polynomial kernel

In [72]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8,gamma='scale')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [73]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

[[88  2]
 [ 2 88]]
              precision    recall  f1-score   support

           2       0.98      0.98      0.98        90
           7       0.98      0.98      0.98        90

    accuracy                           0.98       180
   macro avg       0.98      0.98      0.98       180
weighted avg       0.98      0.98      0.98       180

Training set score: 0.9714
Test set score: 0.9778


# Checking for the classes 8 and 9

In [97]:
def data_prepare(num1,num2):

    df_data2=df_data.iloc[:,:10]
    df_data2['label']=df_data['label']

    df=df_data2[(df_data['label']==num1)|(df_data['label']==num2)]
    label=df['label']
    df=df.drop('label',axis=1)
    return df


In [99]:
df=data_prepare(8,9)
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return floored.astype(np.int)
C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the rele

In [102]:
# Feature scaling

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'linear', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.950


In [101]:
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 0.950


In [94]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'sigmoid', random_state=1, C=0.021,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

Training set score: 0.9476
Test set score: 0.9278


In [95]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'rbf', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
#('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))
#The smaller the value of C, the wider the margins – which may lead to more misclassifications.
##Inversely, the larger the value of C, the more narrow the margins of the classifier become – this may lead to fewer misclassifications
# but higher values of c leads to overfitting

Training set score: 0.9571
Test set score: 0.9500


## Checking for the classes 1 and 9

In [85]:
df_data2=df_data.iloc[:,:10]
df_data2['label']=df_data['label']

df=df_data2[(df_data['label']==1)|(df_data['label']==9)]
label=df['label']
df=df.drop('label',axis=1)

In [86]:
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return floored.astype(np.int)
C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the rele

In [87]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'linear', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

Accuracy: 1.000


In [88]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'sigmoid', random_state=1, C=0.021,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

Training set score: 0.9405
Test set score: 0.9389


In [89]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'rbf', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
#('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))
#The smaller the value of C, the wider the margins – which may lead to more misclassifications.
##Inversely, the larger the value of C, the more narrow the margins of the classifier become – this may lead to fewer misclassifications
# but higher values of c leads to overfitting

Training set score: 0.9810
Test set score: 0.9833


## part 3 of second question 
# multiclass with 10 vs 25 features, cross validation to choose hyperparametes

In [103]:
df_data.shape

(3000, 26)

In [112]:
df=df_data.iloc[:,:25]
label=df_data['label']
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return floored.astype(np.int)
C:\Users\madan\anaconda3\lib\site-packages\sklearn\utils\__init__.py:806: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the rele

In [113]:
X_train.shape

(2100, 25)

In [114]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)## transforming them separately
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'sigmoid', random_state=1, C=0.021,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

Training set score: 0.8090
Test set score: 0.7789


In [118]:
# Train the model; We will train different models using different value of C
#svm = SVC(kernel= 'rbf', random_state=1, C=0.021,gamma='scale')
#svm.fit(X_train_std, y_train)
 
# Measure accuracy score
from sklearn.model_selection import cross_val_score
clf = SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_train,y_train, cv=5)
print(scores)
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

C:\Users\madan\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_folds = np.zeros(n_samples, dtype=np.int)
C:\Users\madan\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review

[0.88571429 0.88095238 0.88333333 0.87857143 0.89285714]
Training set score: 0.8690
Test set score: 0.8411


## Trying with first 10 features

In [129]:
df_data2=df_data.iloc[:,:10]
df_data2['label']=df_data['label']

#df=df_data2[(df_data['label']==1)|(df_data['label']==9)]
label=df_data2['label']
df=df_data2.drop('label',axis=1)
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalanc

In [130]:
from sklearn.model_selection import cross_val_score
clf = SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_train,y_train, cv=5)
print(scores)
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))


[0.82142857 0.80952381 0.82142857 0.8452381  0.85238095]


ValueError: X.shape[1] = 10 should be equal to 25, the number of features at training time